name: Bug Report
description: Something isn't working in Compressor Edge
title: "[BUG] "
labels: ["Bug", "Triage"]
assignees:
  - JoshAtticus
body:
  - type: textarea
    id: description
    attributes:
      label: "Issue Description"
      description: "Please describe your issue with at least 2 sentences or dot points."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behaviour"
      description: "Please describe the behaviour you expected with at least 2 sentences or dot points."
    validations:
      required: true

  - type: textarea
    id: device_info
    attributes:
      label: "Device Info"
      description: |
        All fields marked with an asterisk (*) are required, the rest are optional but strongly recommended.
        Now, please open Compressor Edge, tap the Settings icon in the top right corner, tap "Compressor Edge," scroll down, tap Copy to Clipboard and paste below.
        (If you do not see it, you are using an old version of Compressor Edge. Please update to 1.6.0 or later. You will not receive any support if you are using an older version.)
      value: |
        Device Manufacturer* (e.g. Samsung): 
        - Device Model* (e.g. Galaxy S10): 
        - Android Version* (e.g. 12): 
        - Compressor Edge Version* (e.g. 1.1.0): 
        - Where did you get Compressor Edge from?* (GitHub Releases, IzzyOnDroid/F-Droid, Google Play Store): 
        - Device Chipset (e.g. Exynos 9820): 
        - Device Model Number (e.g. SM-G973F): 
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "Screenshots are required except for when the app does not open."
    validations:
      required: false

  - type: textarea
    id: logcat
    attributes:
      label: "Logcat"
      description: |
        Logcat is STRONGLY recommended, or required if your issue is related to the app not opening/crashing/no error displayed in screenshot. Maintainers are highly likely to ask you for this even if you do not attach it, as it is crucial for finding the issue.
      placeholder: "Drag & drop or paste your logcat here"
    validations:
      required: false

  - type: checkboxes
    id: prerequisites
    attributes:
      label: "Prerequisites"
      description: "Please confirm all of the following before submitting"
      options:
        - label: "I have checked that there are no open issues that are the same or very similar to mine, and I understand that my issue will be closed if it is a duplicate"
          required: true
        - label: "I have filled in all required fields to the best of my ability, and I understand that my issue will be closed if they are not"
          required: true
        - label: "I have copied the device & app info to my clipboard and pasted it into the device info section where indicated, and I understand that my issue will be closed if it is not"
          required: true
        - label: "I have uploaded appropriate screenshots and log files, and I understand that my issue may be closed or remain unresolved if not"
          required: true
        - label: "My issue is written in English, and I understand that my issue will be closed if it is not"
          required: true
        - label: "My issue is not listed in https://github.com/JoshAtticus/CompressorEdge/issues/3"
          required: true
        - label: "I have added a title to my issue"
          required: true
        - label: "I understand that my issue will be closed if all of these checkboxes are not checked"
          required: true
