name: Misc
description: My issue doesn't fall under any of these categories
title: "[MISC] "
labels: ["Misc", "Triage"]
assignees:
  - JoshAtticus
body:
  - type: textarea
    id: issue_content
    attributes:
      label: "Issue Content"
      description: "Please update the issue title and include your issue content below."
    validations:
      required: true
